// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const getMetadata = `-- name: GetMetadata :one
SELECT value FROM centralstore_metadata WHERE key = ?
`

func (q *Queries) GetMetadata(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMetadata, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const putMetadata = `-- name: PutMetadata :exec
INSERT INTO centralstore_metadata (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type PutMetadataParams struct {
	Key   string
	Value string
}

func (q *Queries) PutMetadata(ctx context.Context, arg PutMetadataParams) error {
	_, err := q.db.ExecContext(ctx, putMetadata, arg.Key, arg.Value)
	return err
}
