#!/usr/bin/env bash
# Compute the next release version from unreleased commits, update
# the changelog, and emit release notes for the release PR.
#
# Commit type → section → version bump:
#
#   feat:                   Features   minor
#   perf:                   Features   patch
#   fix:                    Fixes      patch
#   security:               Security   patch
#   docs:                   Docs       no bump on its own
#   feat!: / fix!: /
#     security!: /
#     BREAKING CHANGE:      Breaking   major
#
# Refactor, chore, ci, test, style, build, and revert are skipped
# entirely. See cliff.toml for the full parser rules.
#
# Optional prose for the release goes in RELEASE_HIGHLIGHTS.md at the
# repo root. Its contents are injected into the changelog section
# between the version heading and the grouped bullet lists. The file
# is cleared automatically after each release.
#
# Outputs:
#   stdout         → the next version tag (e.g. v1.2.0), followed by
#                    dry-run previews if --dry-run is set
#   changelog.mdx  → new section inserted above the latest existing
#                    `## v…` heading (unless --dry-run)
#   RELEASE_NOTES.md → highlights + separator + bullets for the
#                      release PR body (unless --dry-run)
#   RELEASE_HIGHLIGHTS.md → reset to stub (unless --dry-run)
#
# Usage:
#   .github/workflows/scripts/version.sh           # apply changes
#   .github/workflows/scripts/version.sh --dry-run # preview only, no writes
set -euo pipefail
trap 'echo "error: ${BASH_SOURCE}:${LINENO}: ${BASH_COMMAND}" >&2' ERR

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
CHANGELOG="$ROOT/apps/website/src/content/docs/changelog.mdx"
HIGHLIGHTS="$ROOT/RELEASE_HIGHLIGHTS.md"

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

# ── Skip release commits ──
#
# Prevents the workflow from re-triggering after merging a release PR.
# Release commits are generated by peter-evans/create-pull-request with
# the exact `release: vX.Y.Z` subject line (and a `(#N)` suffix once
# rebase-merged).

head_msg=$(git log -1 --format='%s')
if [[ "$head_msg" =~ ^release:\ v[0-9] ]]; then
  echo "Release commit, skipping." >&2
  exit 0
fi

# ── Require git-cliff ──

if ! command -v git-cliff >/dev/null 2>&1; then
  echo "error: git-cliff is not installed. Install it with: cargo install git-cliff" >&2
  exit 1
fi

# ── Check for releasable commits ──
#
# git-cliff's --bump defaults to a patch bump whenever any tracked
# commit exists (including docs-only releases). We only release when
# there's at least one commit in a Features, Fixes, Breaking, or
# Security group.
#
# git-cliff exits 0 with `[]` on stdout when there are no unreleased
# commits (logging a warning to stderr). Real failures (missing
# binary, broken cliff.toml) surface via `set -e` because the command
# substitution inherits the exit status.

context=$(git-cliff --unreleased --bump --context)
releasable_count=$(echo "$context" | jq '
  if length == 0 then 0
  else [.[0].commits[] | select(.group | test("Features|Fixes|Breaking|Security"))] | length
  end
')

last_tag=$(git tag -l 'v*' | sort -V | tail -1)
last_tag="${last_tag:-v0.0.0}"

if [[ "${releasable_count:-0}" -eq 0 ]]; then
  echo "No releasable commits since ${last_tag}." >&2
  exit 0
fi

new_version=$(echo "$context" | jq -r '.[0].version')

# ── Generate changelog section ──
#
# Produces:
#   ## vX.Y.Z
#
#   ### Features
#   - foo ([#N](https://github.com/gmuxapp/gmux/pull/N))
#
#   ### Fixes
#   - bar ([#N](https://github.com/gmuxapp/gmux/pull/N))
#
#   ---

section=$(git-cliff --unreleased --bump)

# ── Helper: strip leading and trailing blank lines ──

trim_blanks() {
  awk '
    { lines[NR] = $0 }
    END {
      first = 1
      while (first <= NR && lines[first] ~ /^[[:space:]]*$/) first++
      last = NR
      while (last >= first && lines[last] ~ /^[[:space:]]*$/) last--
      for (i = first; i <= last; i++) print lines[i]
    }
  '
}

# ── Read highlights (optional prose for the release) ──

# Strip HTML comment blocks (single- or multi-line) from the highlights
# file. A naive `sed '/<!--/,/-->/d'` swallows everything after an
# inline `<!-- ... -->` because sed won't match start and end on the
# same line. This awk version tracks comment state correctly.
strip_html_comments() {
  awk '
    {
      line = $0
      out = ""
      while (length(line) > 0) {
        if (in_comment) {
          end = index(line, "-->")
          if (end == 0) { line = ""; break }
          line = substr(line, end + 3)
          in_comment = 0
        } else {
          start = index(line, "<!--")
          if (start == 0) { out = out line; line = ""; break }
          out = out substr(line, 1, start - 1)
          line = substr(line, start + 4)
          in_comment = 1
        }
      }
      if (!in_comment || length(out) > 0) print out
    }
  '
}

highlights=""
if [[ -s "$HIGHLIGHTS" ]]; then
  highlights=$(strip_html_comments < "$HIGHLIGHTS" | trim_blanks)
fi

# ── Compose RELEASE_NOTES.md ──
#
# Format:
#
#   <highlights prose>
#
#   <!-- highlights-end -->
#
#   ### Features
#   - ...
#
#   ### Fixes
#   - ...
#
# The `<!-- highlights-end -->` marker is invisible in rendered
# markdown (so GoReleaser's GitHub Release body and the release PR
# body look clean), and `notify-discord.sh` extracts everything before
# it as the Discord summary. Unlike a literal `---`, an HTML comment
# never collides with user prose (horizontal rules, YAML frontmatter).

# Reuse git-cliff's heading line verbatim so we pick up the date suffix.
heading=$(echo "$section" | sed -n '/^## v/{p;q;}')
bullets=$(echo "$section" | awk '
  /^## v/ { in_section = 1; next }
  /^---$/ { in_section = 0 }
  in_section { print }
' | trim_blanks)

release_notes=""
if [[ -n "$highlights" ]]; then
  release_notes+="${highlights}"$'\n\n'
fi
release_notes+="<!-- highlights-end -->"$'\n\n'"${bullets}"

# ── Compose changelog.mdx entry ──
#
# Format (matches the historical layout):
#
#   ## vX.Y.Z - 2026-04-10
#
#   <highlights prose>
#
#   ### Features
#   - ...
#
#   ---

changelog_entry="${heading}"$'\n'
if [[ -n "$highlights" ]]; then
  changelog_entry+=$'\n'"${highlights}"$'\n'
fi
changelog_entry+=$'\n'"${bullets}"$'\n\n'"---"

# ── Output ──

echo "$new_version"

if $DRY_RUN; then
  echo ""
  echo "── changelog.mdx entry ──"
  echo "$changelog_entry"
  echo ""
  echo "── RELEASE_NOTES.md ──"
  echo "$release_notes"
  exit 0
fi

# ── Write RELEASE_NOTES.md ──

printf '%s\n' "$release_notes" > "$ROOT/RELEASE_NOTES.md"

# ── Update changelog.mdx ──
#
# Insert new version section before the first "## v" heading.
# If no such heading exists, append to the end.

if grep -q '^## v[0-9]' "$CHANGELOG"; then
  awk -v entry="$changelog_entry" '
    !inserted && /^## v[0-9]/ {
      printf "%s\n", entry
      inserted = 1
    }
    { print }
  ' "$CHANGELOG" > "$CHANGELOG.tmp"
else
  cp "$CHANGELOG" "$CHANGELOG.tmp"
  printf '\n%s\n' "$changelog_entry" >> "$CHANGELOG.tmp"
fi
mv "$CHANGELOG.tmp" "$CHANGELOG"

# ── Clear RELEASE_HIGHLIGHTS.md ──
#
# The release PR includes the cleared state so the next cycle starts
# fresh. The stub content explains the workflow to future editors.

cat > "$HIGHLIGHTS" <<'STUB'
<!--
Optional prose for the next release. Edit this file to add a high-level
summary, topic paragraphs, or migration notes. When version.sh runs, the
content is injected into the changelog section between the version
heading and the grouped bullet lists.

The file is cleared automatically after each release. Leave empty for
releases that don't need prose (the auto-generated bullet list is
enough for patch-only releases).

Format: plain markdown. Supports headings, paragraphs, and lists.
Example:

    Peers now automatically reconnect after system suspend, no restart
    needed.

    ### Project matching
    `projects.json` replaces separate `remote` and `paths` fields with a
    unified `match` array.
-->
STUB

echo "Updated $CHANGELOG" >&2
echo "Updated $HIGHLIGHTS (cleared)" >&2
